# Generated by Django 2.1.4 on 2018-12-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizlogic', '0002_auto_20181211_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bcity',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bdistrict',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bprovince',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ciautotextsql',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cidblinkdefine',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ciexception',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cifile',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cifolder',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ciitemdetails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ciitems',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cilog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cimessage',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ciparameter',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cisequence',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='citablecolumns',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dboperationdetaillog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='dboperationlog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pimodule',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='piorganize',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pipermission',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pipermissionitem',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pipermissionscope',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='piplatformaddin',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pirole',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pistaff',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pistafforganize',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pitablepermissionscope',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='piuser',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='piuserlogon',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='piuserorganize',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='piuserrole',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='piuserv27',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='queryengine',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='queryenginedefine',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tbleave',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='zdnationcode',
            options={'managed': True},
        ),
    ]
