# Generated by Django 2.1.4 on 2018-12-18 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bizlogic', '0003_auto_20181212_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pistaff',
            name='id',
            field=models.CharField(db_column='ID', default=uuid.UUID('6ffcdec2-0290-11e9-b06c-10c37b919c5d'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pistafforganize',
            name='id',
            field=models.CharField(db_column='ID', default=uuid.UUID('f32b56aa-7c75-458a-ac6d-358c4d933ab1'), max_length=40, primary_key=True, serialize=False),
        ),
    ]
