# Generated by Django 2.1.4 on 2018-12-26 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bizlogic', '0004_auto_20181218_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cifile',
            name='filecontent',
            field=models.BinaryField(blank=True, db_column='FILECONTENT', null=True),
        ),
        migrations.AlterField(
            model_name='pipermissionitem',
            name='allowdelete',
            field=models.IntegerField(db_column='ALLOWDELETE', default=1),
        ),
        migrations.AlterField(
            model_name='pipermissionitem',
            name='allowedit',
            field=models.IntegerField(db_column='ALLOWEDIT', default=1),
        ),
        migrations.AlterField(
            model_name='pipermissionitem',
            name='categorycode',
            field=models.CharField(db_column='CATEGORYCODE', default='Application', max_length=50),
        ),
        migrations.AlterField(
            model_name='pipermissionitem',
            name='deletemark',
            field=models.IntegerField(db_column='DELETEMARK', default=0),
        ),
        migrations.AlterField(
            model_name='pipermissionitem',
            name='enabled',
            field=models.IntegerField(db_column='ENABLED', default=1),
        ),
        migrations.AlterField(
            model_name='pipermissionitem',
            name='ispublic',
            field=models.IntegerField(db_column='ISPUBLIC', default=0),
        ),
        migrations.AlterField(
            model_name='pipermissionitem',
            name='isscope',
            field=models.IntegerField(db_column='ISSCOPE', default=0),
        ),
        migrations.AlterField(
            model_name='pipermissionitem',
            name='issplit',
            field=models.IntegerField(db_column='ISSPLIT', default=0),
        ),
        migrations.AlterField(
            model_name='pistaff',
            name='id',
            field=models.CharField(db_column='ID', default=uuid.UUID('e5d80fe2-08ad-11e9-ba0c-10c37b919c5d'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pistafforganize',
            name='id',
            field=models.CharField(db_column='ID', default=uuid.UUID('25553afd-5fa2-4e31-8408-30b241d8f4ea'), max_length=40, primary_key=True, serialize=False),
        ),
    ]
